categories:
- Convert Formats
description: Converts genetic sequences between different formats
homepage_url: <http://itaxotools.org>
long_description: 'Supported formats: tab: [Internal tab format], tab_noheaders: [Internal
  tab format] without headers, fasta: FASTA format, relaxed_phylip: relaxed Phylip
  format, fasta_hapview: FASTA format for Haplotype Viewer, phylip: Phylip format,
  fastq: FASTQ format, fasta_gbexport: FASTA format for export into Genbank repository,
  nexus: NEXUS format, nexml: DnaCharacterMatrix in NeXML format, genbank: Genbank
  flat file format, mold_fasta: FASTA format with sequence name matching requirements
  for the tool MolD.'
name: dna_convert
owner: ffischell
