categories:
- Phylogenetics
description: Identify robust sets of diagnostic sites for pre-defined taxa from DNA sequences
homepage_url: <http://itaxotools.org>
long_description: MolD 1.4 is tailored to seamlessly recover DNA-based diagnoses from large DNA datasets and is capable of identifying diagnostic combinations of nucleotides (DNCs) in addition to single (pure) diagnostic sites, enabling users to base DNA diagnoses on a minimal number of diagnostic sites necessary for a reliable differentiation of taxa, rather than providing a long list of such sites. The MolD algorithm assembles DNA diagnoses that fulfill pre-defined criteria of reliability, which is achieved by repeatedly scoring diagnostic nucleotide combinations against datasets of in silico mutated sequences. 
name: mold
owner: ffischell
